### ISSUE TITLE
min number of Juror by court

### ISSUE THREAD

**Issue by salgozino** [salgozino/KlerosJurorDashboard#1]
I'm considering the number of juror for each case as 3, because I don't know where I can find the correct minimum number of jurors defined in each court.

**Comment by dylancaponi** [comment]
Where is this number hardcoded in the repo?

**Comment by salgozino** [comment]
In [Kleros.py](https://github.com/salgozino/KlerosJurorDashboard/blob/9c9d04cdb03e41165ab074e67ed01aea9edad1b2/app/modules/Kleros.py#L80). I estimates the chances by court, calling the function chanceCalculator and that function takes nJurors as argument. By default it's 3, but this maybe will depend on each court. AFAIK, the minimum number of jurors it's 3 in all the courts right now, but this could be changed by governance in the future.

Now I notice that Kleros.py has a class defined, but it's not necesary because I use it as a module. I will fix that.

**Comment by ferittuncer** [comment]
I think a better stat would be to have a calculation of your chance of being drawn per single vote instead of three votes. Users can multiply this by the number of votes. Consider appeals for example.

Also, I recommend replacing the 'number of jurors' jargon with 'number of votes' jargon, because, in reality, it's the number of votes, there doesn't have to be N distinct jurors. This is often confused by community members and they are surprised to see that a juror is drawn multiple times in a dispute.

**Comment by salgozino** [comment]
Thank you for the clarification @ferittuncer on the min jurors parameter.
Since the issue was raised is true that most of the disputes starts with 3 jurors, but in Linguo for instance is just one. And it's true that the odds calculator doesn't allow to understand your odds in different appeal rounds.

The odds to be drawn is exponential with the number of jurors in the round.  The maths could be check here: https://github.com/salgozino/KlerosJurorDashboard/blob/9c9d04cdb03e41165ab074e67ed01aea9edad1b2/app/modules/Kleros.py#L99
I don't know if putting the odds in term of just one vote will be intuitive for all the users, because is not just to multiply by the number of jurors. Maybe, the best solution is to add in the interface the amount of jurors for the calculator (with 3 as default value), so the users could check by themself in different conditions. What do you think?.

I agree in the missunderstandings of the users due to the jargon of vote/juror, I will update this.

**Comment by ferittuncer** [comment]
Sorry for the late reply. Parameterizing this and having input from users is a good idea, indeed.

The calculator calculates odds to be drawn at least once in a dispute. That's why it's not linear, but I would argue that it's not what we want to know actually. For me, each vote is a lottery, and for a dispute with 3 votes, there are 3 lotteries. As a staked user, I have tickets for each lottery, and I want to know the odds of winning in an individual lottery. Luckily odds for all lotteries are the same. So if you think this way both of the following scenarios are the same in terms of profitability:

1 dispute with 10 votes.
10 disputes with 1 vote each.

That's why I'm interested in the basic unit of this calculation: "What are the odds for me to have a single vote in this dispute?"
