### ISSUE TITLE
Odds Over 100%

### ISSUE THREAD

**Issue by dylancaponi** [salgozino/KlerosJurorDashboard#17]
In the Juror Odds tab many courts show over 100% for 10000PNK staked.
Should odds be capped at 100%?

**Comment by dylancaponi** [comment]
Ah, I see there's supposed to be a [tooltip message](https://github.com/salgozino/KlerosJurorDashboard/blob/9424df1d3b413775c0449299d9ba5bfe13b398f9/app/templates/odds.html#L37) but this is not showing up for me on Chrome.

**Comment by salgozino** [comment]
I use Chrome and Firefox and in both browser the tooltip show up. It's a small question black questionmark in following the percentage. In the cellphone is showed too.

![tooltip](https://user-images.githubusercontent.com/9450450/95029127-709d4b00-067c-11eb-9486-c1c69b9250b1.png)

I think that the percentage has not to be capped, because if you have 200% chances, means that most probably you will have 2 votes in the round.
