### ISSUE TITLE
Fee For Juror

### ISSUE THREAD

**Issue by 0xferit** [salgozino/KlerosJurorDashboard#74]
It's actually fee per vote. Better jargon would make it easier to understand for people who are just introduced to Kleros.

Another problem is, the data on Klerosboard is still wrong about fees. It's a long standing problem, AFAIK it's been a few months now. As it's misleading, I suggest you to prioritize this issue.

**Comment by salgozino** [comment]
I've fixed the wording and the fix for the subgraphs it's on it's way.

The delay was mainly because the subgraph issue is not very straightforward where is happening so takes me really long time to found a fix.
Most probably today the subgraph will end up syncing and the dashboard will be displaying the right values.
